git:
  # Username or token
  user: ""
  # Password or token (if using token, use it as both user and pass)
  pass: ""
  # Repository URL
  repo: ""
  # Selected branch, default is master or main
  # Use this to set up development servers, production servers, and test servers and the like
  # This has an effect on everything from pushing, pulling, and webhooks
  branch: "master"

# Whether experimental jar unloading and loading should be enabled
# This requires PlugManX to be installed and working on your server
# This is experimental and may cause issues!
# Will inevitably cause a lot of issues if used on library or core plugins
# Requires you to remove "*.jar" from the .gitignore file in your server root
experimental-jar-loading: true

bossbar:
  # Whether to enable the boss bar
  enabled: true
  # How long the action result should be visible for, in ticks (20 ticks = 1 second)
  # High values here WILL delay further commands of the same type
  duration: 100

# Filtering in the config is obsolete with V2
# See the .gitignore file in your server root for filtering
# See https://git-scm.com/docs/gitignore for more information

webhooks:
  # Will listen at http://<your server ip>:<port>/<path>
  # The port to listen on, set to 0 to disable
  port: 8080
  # The path to listen on
  path: "minecicd"

  # Webhook listener configuration
  # minecicd.notify is used for identifying who to notify when a webhook event is received
  # Order of execution:
  # 1. Commands / Scripts are executed with operator permissions
  # 2. One of the following is executed (in this order):
  #   - restart
  #   - global reload
  #   - individual reload
  allow-commands: true # This allows to execute arbitrary commands on the server, it is recommended to disable this on production servers
  allow-scripts: true # This allows to execute arbitrary CICD scripts on the server, it is recommended to disable this on production servers
  allow-individual-reload: true # This might not work with all plugins, issues will be displayed in the console. It is recommended to disable this on production servers
  allow-global-reload: false # This is highly discouraged, as it can cause issues with many plugins
  allow-restart: true
